### ISSUE TITLE
Cannot build public folder from sources

### ISSUE THREAD

**Issue by FM-uib** [adityaathalye/shite#8]
Hi
Thank you for building this. I wanted to give shite a try, but I cant seem to get it to work properly that it builds the public directory from the sources files provided in the repo.

I tried `./shite.sh "no" ` 
which gives me this:

`2022-11-15T23:07:09+01:00 INFO ./shite.sh Hotreloadin' your shite now! '{"watch_dir": "/home/SOMEPATH/shite", "tab_name": "", "browser_name": "Mozilla Firefox", "base_url": "file:///home/SOMEPATH/shite/public", "window_id": "39845950"}'
-m and -t cannot both be specified.
`

I tried calling `shite_templating_publish_sources()` directly, but it just seems to not do anything. 

Any clue what I am doring wrong?

**Comment by adityaathalye** [comment]
Hi! Thanks for writing in!

I see `shite` is delivering on its quality promise :)

I'm away from computer, but I'd try one or both of these:

- Search the code for a command invocation with `-m` and `-t` both.
- If that isn't conclusive, I'd use `set +x` and `set -x` to trace
execution. The problem code should appear in the trace.

My first guess is that the offending command or utility behaves differently
on your OS. I use Ubuntu 22.04 LTS and whatever GNU core utils live in it.

Once you find the problem invocation, try modifying the flags so it
continues to do the desired job. The util's manpage should help.

Happy hunting!

**Comment by FM-uib** [comment]
I am running ubuntu 20.04. 
Found the culprit. it was in events.sh. removing the --timeout flag from the inotifywait call made it work.

**Comment by adityaathalye** [comment]
Glad you found a solution! How did you figure it out? Search or trace?

That's weird though... inotifywait doesn't annoy me like that. The version on my box is `inotifywait 3.22.1.0`.
